export const COUNTRY_LISTING_ROUTE = '/index';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const CLOSE_ALERT = 'CLOSE_ALERT';
export const GET_CHECKED = 'GET_CHECKED';

export const CHECK_USER_REQUESTED = 'CHECK_USER_REQUESTED';
export const CHECK_USER_SUCCESSED = 'CHECK_USER_SUCCESSED';
export const CHECK_USER_FAILED = 'CHECK_USER_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESSED = 'USER_LOGOUT_SUCCESSED';

export const LIST_REQUESTED = 'LIST_REQUESTED';
export const LIST_SUCCESSED = 'LIST_SUCCESSED';
export const LIST_FAILED = 'LIST_FAILED';
